### PR TITLE
Feat: Option to add Citations / Footnote Counts

### PR DESCRIPTION
**Pull request by chrisgrieser**
Implements #57, essentially sherlocking the [footnote indicator plugin](https://github.com/chrisgrieser/obsidian-footnote-indicator/blob/master/main.ts)

### CODE REVIEW

**Comment by chrisgrieser** [comment]
Thx! Since the update should be relevant to a bunch of academic writers, (and also deprecates the footnote indicator plugin), it probably makes sense to announce it at Discord. 

Would you do so? Otherwise, I can also announce do it.

**Comment by lukeleppan** [comment]
No thank you. Sorry it took me so long to get to. You are more than welcome to announce it on the discord, please make sure to credit yourself for the update. 

I think there seems to be a bug with stat collection that occurs when updating that will stop the daily footnotes from working. Its likely that this bug fixes itself the day after updating. So let's hope no one notices, until there's a fix. Or maybe you can mention it in the announcement.

For the past few months of been thinking of a way to make it easier to add new features to the plugin (I'm sure you noticed how awful the current implementation is). So some much needed refactoring in in order. So that's why I didn't announce anything.

Thank you again.

**Comment by chrisgrieser** [comment]
No problem! I just made the announcement: https://discord.com/channels/686053708261228577/855181471643861002/1091015264205803540

Yeah, it was a bit cumbersome to find all the places where I would have to add footnotes & citations, but in the end, that resulted in various kinds of features i did not have to write myself, like for example counting footnotes/citations in the selected text. Or even counting your daily written footnotes 😜

**Comment by Gewerd-Strauss** [comment]
There are bugs with  whatever needle parses for citations and/or footnotes:

Given

    [@altschul2001blast] 
    [@10.1371/journal.pone.0032097] 
    [@10.1093/nar/gkaa913] 
    [@Melcher2016]
    
The plugin will return 2 citations - those are `Melcher2016` and `altschul2001blast`. 

Further testing suggested that keys containing 
* dots \*
* Exclamation marks

do not get recognised.

---

Additionally, 
    
    e[^1][^2]  
    e[^3].[^4]  
    e[^3],[^4]  
    e[^3]a[^4]  
    e[^3]3[^4]
    
THese will all not count the second footnote. Adding a space inbetween the footnotes will result in them being counted. 

---

\* I have actual citations that contain them, not just made-up test data.

**Comment by chrisgrieser** [comment]
@Gewerd-Strauss I think pandoc (without addons) treats those doi-URLs as invalid citation keys? And iirc, multi-footnotes like that are also not (universally) supported. I tried to add only the basic standard for both, to reduce ambiguity.

Anyway, feature requests to support your cases do not belong in the discussion of a PR, but to an issue. Probably falls under the same category as #81

**Comment by lukeleppan** [comment]
> No problem! I just made the announcement: https://discord.com/channels/686053708261228577/855181471643861002/1091015264205803540

Awesome, what did you use to make that screenshot?

**Comment by chrisgrieser** [comment]
You mean the annotated screenshots? I am on mac and use CleanShot X (one-time-payment). Alternatively, there is also Shottr (free), which also allows such annotations.

If you are on Linux, I know there is Flameshot. No idea what people use for that on Windows 🙈

**Pull request merged**
