### PR TITLE
Recognize apostrophes as being part of a word.

### PR DESCRIPTION
**Pull request by turnage**
Fix for #36. I tested this locally:

Screen Shot 2021-12-24 at 10 07 33 AM

### CODE REVIEW

**Comment by lukeleppan** [comment]
Hi thanks for the PR. I will take a look at the changes today. With regards to the way words are counted. I try to keep the method the same as the default word count plugin (aside from the optional changes, e.g. "Don't count comments". Could you please do me a favour and check if the default plugin treats compound words as 2 words? I wouldn't want to stray from the default. 

I realise now that it may be an opinionated option. So maybe it would be best to implement it as an optional change to the word count method. Let me know what you think.

**Comment by turnage** [comment]
I understand you don't want to defy user expectations. Fwiw I have no idea why the default word count plugin counts `don't` as two words---can't think of a valid use case---but it makes the word count inaccurate/unusuable for most English prose.

I used it to edit a fiction submission down to a specified wordcount and then when I moved it into scrivener I discovered I undershot the wordcount target by 50 words.

It was reported as a bug a long time ago but hasn't gotten any attention: https://forum.obsidian.md/t/incorrect-word-count-from-apostrophes/14156

I submitted a fix here just because the devs didn't respond to the bug report for the main product.

A toggle option is no problem for me personally, just wanted to provide some more context for your decision.

**Comment by colintedford** [comment]
Confirmed that the default word count plugin still treats compound words as 2 words in the new editor. :(

**Comment by turnage** [comment]
Update: the devs responded to the bug report; Obsidian's default word counter is going to fix this.

**Comment by lukeleppan** [comment]
Wow I have no idea how this slipped under my radar will test this ASAP and merge. Thank you and sorry.

**Comment by lukeleppan** [comment]
I merged it thank you @turnage sorry it took me 11 months. As I have mentioned previously I did step away from the plugin but I am back now so yes. Thank you.

**Pull request merged**
